@thulite/doks-core v1.8.1 fails with: (#393)
Error: error building site:
"D:\git\ocm\ocm-website\node_modules\@thulite\doks-core\layouts\_default\_markup\render-codeblock-kroki.html:56:1":
parse failed: template: _default/_markup/render-codeblock-kroki.html:56:
function "try" not defined

<!-- markdownlint-disable MD041 -->
#### What this PR does / why we need it

revert https://github.com/open-component-model/ocm-website/pull/392
because publish fails:


https://github.com/open-component-model/ocm-website/actions/runs/13236063660

#### Which issue(s) this PR fixes
<!--
Usage: `Fixes #<issue number>`, or `Fixes (paste link of issue)`.
-->